from app.routers import (
    agro_plan,
    auth,
    dashboard,
    employee_rates,
    employees,
    equipment_logs,
    expenses,
    fields,
    implements,
    inventory,
    maintenance,
    notifications,
    references,
    reports,
    settings as settings_router,
    sharing,
    shipments,
    shifts,
    superadmin,
)

__all__ = [
    'agro_plan',
    'auth',
    'dashboard',
    'employee_rates',
    'employees',
    'equipment_logs',
    'expenses',
    'fields',
    'implements',
    'inventory',
    'maintenance',
    'notifications',
    'references',
    'reports',
    'settings_router',
    'sharing',
    'shipments',
    'shifts',
    'superadmin',
]
