/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './app/routes/__root'
import { Route as LoginRouteImport } from './app/routes/login'
import { Route as LayoutRouteImport } from './app/routes/_layout'
import { Route as LayoutIndexRouteImport } from './app/routes/_layout/index'
import { Route as LayoutDashboardRouteImport } from './app/routes/_layout/dashboard'
import { Route as LayoutWorktimeIndexRouteImport } from './app/routes/_layout/worktime/index'
import { Route as LayoutShipmentsIndexRouteImport } from './app/routes/_layout/shipments/index'
import { Route as LayoutSettingsIndexRouteImport } from './app/routes/_layout/settings/index'
import { Route as LayoutReportsIndexRouteImport } from './app/routes/_layout/reports/index'
import { Route as LayoutProfileIndexRouteImport } from './app/routes/_layout/profile/index'
import { Route as LayoutMyShiftIndexRouteImport } from './app/routes/_layout/my-shift/index'
import { Route as LayoutInventoryIndexRouteImport } from './app/routes/_layout/inventory/index'
import { Route as LayoutExpensesIndexRouteImport } from './app/routes/_layout/expenses/index'
import { Route as LayoutEmployeesIndexRouteImport } from './app/routes/_layout/employees/index'

const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const LayoutRoute = LayoutRouteImport.update({
  id: '/_layout',
  getParentRoute: () => rootRouteImport,
} as any)
const LayoutIndexRoute = LayoutIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => LayoutRoute,
} as any)
const LayoutDashboardRoute = LayoutDashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => LayoutRoute,
} as any)
const LayoutWorktimeIndexRoute = LayoutWorktimeIndexRouteImport.update({
  id: '/worktime/',
  path: '/worktime/',
  getParentRoute: () => LayoutRoute,
} as any)
const LayoutShipmentsIndexRoute = LayoutShipmentsIndexRouteImport.update({
  id: '/shipments/',
  path: '/shipments/',
  getParentRoute: () => LayoutRoute,
} as any)
const LayoutSettingsIndexRoute = LayoutSettingsIndexRouteImport.update({
  id: '/settings/',
  path: '/settings/',
  getParentRoute: () => LayoutRoute,
} as any)
const LayoutReportsIndexRoute = LayoutReportsIndexRouteImport.update({
  id: '/reports/',
  path: '/reports/',
  getParentRoute: () => LayoutRoute,
} as any)
const LayoutProfileIndexRoute = LayoutProfileIndexRouteImport.update({
  id: '/profile/',
  path: '/profile/',
  getParentRoute: () => LayoutRoute,
} as any)
const LayoutMyShiftIndexRoute = LayoutMyShiftIndexRouteImport.update({
  id: '/my-shift/',
  path: '/my-shift/',
  getParentRoute: () => LayoutRoute,
} as any)
const LayoutInventoryIndexRoute = LayoutInventoryIndexRouteImport.update({
  id: '/inventory/',
  path: '/inventory/',
  getParentRoute: () => LayoutRoute,
} as any)
const LayoutExpensesIndexRoute = LayoutExpensesIndexRouteImport.update({
  id: '/expenses/',
  path: '/expenses/',
  getParentRoute: () => LayoutRoute,
} as any)
const LayoutEmployeesIndexRoute = LayoutEmployeesIndexRouteImport.update({
  id: '/employees/',
  path: '/employees/',
  getParentRoute: () => LayoutRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof LayoutIndexRoute
  '/login': typeof LoginRoute
  '/dashboard': typeof LayoutDashboardRoute
  '/employees/': typeof LayoutEmployeesIndexRoute
  '/expenses/': typeof LayoutExpensesIndexRoute
  '/inventory/': typeof LayoutInventoryIndexRoute
  '/my-shift/': typeof LayoutMyShiftIndexRoute
  '/profile/': typeof LayoutProfileIndexRoute
  '/reports/': typeof LayoutReportsIndexRoute
  '/settings/': typeof LayoutSettingsIndexRoute
  '/shipments/': typeof LayoutShipmentsIndexRoute
  '/worktime/': typeof LayoutWorktimeIndexRoute
}
export interface FileRoutesByTo {
  '/login': typeof LoginRoute
  '/dashboard': typeof LayoutDashboardRoute
  '/': typeof LayoutIndexRoute
  '/employees': typeof LayoutEmployeesIndexRoute
  '/expenses': typeof LayoutExpensesIndexRoute
  '/inventory': typeof LayoutInventoryIndexRoute
  '/my-shift': typeof LayoutMyShiftIndexRoute
  '/profile': typeof LayoutProfileIndexRoute
  '/reports': typeof LayoutReportsIndexRoute
  '/settings': typeof LayoutSettingsIndexRoute
  '/shipments': typeof LayoutShipmentsIndexRoute
  '/worktime': typeof LayoutWorktimeIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/_layout': typeof LayoutRouteWithChildren
  '/login': typeof LoginRoute
  '/_layout/dashboard': typeof LayoutDashboardRoute
  '/_layout/': typeof LayoutIndexRoute
  '/_layout/employees/': typeof LayoutEmployeesIndexRoute
  '/_layout/expenses/': typeof LayoutExpensesIndexRoute
  '/_layout/inventory/': typeof LayoutInventoryIndexRoute
  '/_layout/my-shift/': typeof LayoutMyShiftIndexRoute
  '/_layout/profile/': typeof LayoutProfileIndexRoute
  '/_layout/reports/': typeof LayoutReportsIndexRoute
  '/_layout/settings/': typeof LayoutSettingsIndexRoute
  '/_layout/shipments/': typeof LayoutShipmentsIndexRoute
  '/_layout/worktime/': typeof LayoutWorktimeIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/login'
    | '/dashboard'
    | '/employees/'
    | '/expenses/'
    | '/inventory/'
    | '/my-shift/'
    | '/profile/'
    | '/reports/'
    | '/settings/'
    | '/shipments/'
    | '/worktime/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/login'
    | '/dashboard'
    | '/'
    | '/employees'
    | '/expenses'
    | '/inventory'
    | '/my-shift'
    | '/profile'
    | '/reports'
    | '/settings'
    | '/shipments'
    | '/worktime'
  id:
    | '__root__'
    | '/_layout'
    | '/login'
    | '/_layout/dashboard'
    | '/_layout/'
    | '/_layout/employees/'
    | '/_layout/expenses/'
    | '/_layout/inventory/'
    | '/_layout/my-shift/'
    | '/_layout/profile/'
    | '/_layout/reports/'
    | '/_layout/settings/'
    | '/_layout/shipments/'
    | '/_layout/worktime/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  LayoutRoute: typeof LayoutRouteWithChildren
  LoginRoute: typeof LoginRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_layout': {
      id: '/_layout'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof LayoutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_layout/': {
      id: '/_layout/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof LayoutIndexRouteImport
      parentRoute: typeof LayoutRoute
    }
    '/_layout/dashboard': {
      id: '/_layout/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof LayoutDashboardRouteImport
      parentRoute: typeof LayoutRoute
    }
    '/_layout/worktime/': {
      id: '/_layout/worktime/'
      path: '/worktime'
      fullPath: '/worktime/'
      preLoaderRoute: typeof LayoutWorktimeIndexRouteImport
      parentRoute: typeof LayoutRoute
    }
    '/_layout/shipments/': {
      id: '/_layout/shipments/'
      path: '/shipments'
      fullPath: '/shipments/'
      preLoaderRoute: typeof LayoutShipmentsIndexRouteImport
      parentRoute: typeof LayoutRoute
    }
    '/_layout/settings/': {
      id: '/_layout/settings/'
      path: '/settings'
      fullPath: '/settings/'
      preLoaderRoute: typeof LayoutSettingsIndexRouteImport
      parentRoute: typeof LayoutRoute
    }
    '/_layout/reports/': {
      id: '/_layout/reports/'
      path: '/reports'
      fullPath: '/reports/'
      preLoaderRoute: typeof LayoutReportsIndexRouteImport
      parentRoute: typeof LayoutRoute
    }
    '/_layout/profile/': {
      id: '/_layout/profile/'
      path: '/profile'
      fullPath: '/profile/'
      preLoaderRoute: typeof LayoutProfileIndexRouteImport
      parentRoute: typeof LayoutRoute
    }
    '/_layout/my-shift/': {
      id: '/_layout/my-shift/'
      path: '/my-shift'
      fullPath: '/my-shift/'
      preLoaderRoute: typeof LayoutMyShiftIndexRouteImport
      parentRoute: typeof LayoutRoute
    }
    '/_layout/inventory/': {
      id: '/_layout/inventory/'
      path: '/inventory'
      fullPath: '/inventory/'
      preLoaderRoute: typeof LayoutInventoryIndexRouteImport
      parentRoute: typeof LayoutRoute
    }
    '/_layout/expenses/': {
      id: '/_layout/expenses/'
      path: '/expenses'
      fullPath: '/expenses/'
      preLoaderRoute: typeof LayoutExpensesIndexRouteImport
      parentRoute: typeof LayoutRoute
    }
    '/_layout/employees/': {
      id: '/_layout/employees/'
      path: '/employees'
      fullPath: '/employees/'
      preLoaderRoute: typeof LayoutEmployeesIndexRouteImport
      parentRoute: typeof LayoutRoute
    }
  }
}

interface LayoutRouteChildren {
  LayoutDashboardRoute: typeof LayoutDashboardRoute
  LayoutIndexRoute: typeof LayoutIndexRoute
  LayoutEmployeesIndexRoute: typeof LayoutEmployeesIndexRoute
  LayoutExpensesIndexRoute: typeof LayoutExpensesIndexRoute
  LayoutInventoryIndexRoute: typeof LayoutInventoryIndexRoute
  LayoutMyShiftIndexRoute: typeof LayoutMyShiftIndexRoute
  LayoutProfileIndexRoute: typeof LayoutProfileIndexRoute
  LayoutReportsIndexRoute: typeof LayoutReportsIndexRoute
  LayoutSettingsIndexRoute: typeof LayoutSettingsIndexRoute
  LayoutShipmentsIndexRoute: typeof LayoutShipmentsIndexRoute
  LayoutWorktimeIndexRoute: typeof LayoutWorktimeIndexRoute
}

const LayoutRouteChildren: LayoutRouteChildren = {
  LayoutDashboardRoute: LayoutDashboardRoute,
  LayoutIndexRoute: LayoutIndexRoute,
  LayoutEmployeesIndexRoute: LayoutEmployeesIndexRoute,
  LayoutExpensesIndexRoute: LayoutExpensesIndexRoute,
  LayoutInventoryIndexRoute: LayoutInventoryIndexRoute,
  LayoutMyShiftIndexRoute: LayoutMyShiftIndexRoute,
  LayoutProfileIndexRoute: LayoutProfileIndexRoute,
  LayoutReportsIndexRoute: LayoutReportsIndexRoute,
  LayoutSettingsIndexRoute: LayoutSettingsIndexRoute,
  LayoutShipmentsIndexRoute: LayoutShipmentsIndexRoute,
  LayoutWorktimeIndexRoute: LayoutWorktimeIndexRoute,
}

const LayoutRouteWithChildren =
  LayoutRoute._addFileChildren(LayoutRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  LayoutRoute: LayoutRouteWithChildren,
  LoginRoute: LoginRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
