/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './app/routes/__root'
import { Route as LoginRouteImport } from './app/routes/login'
import { Route as LayoutRouteImport } from './app/routes/_layout'
import { Route as SuperadminRouteRouteImport } from './app/routes/superadmin/route'
import { Route as IndexRouteImport } from './app/routes/index'
import { Route as LandingIndexRouteImport } from './app/routes/landing/index'
import { Route as SuperadminLoginRouteImport } from './app/routes/superadmin/login'
import { Route as SuperadminAuthenticatedRouteImport } from './app/routes/superadmin/_authenticated'
import { Route as LayoutDashboardRouteImport } from './app/routes/_layout/dashboard'
import { Route as LayoutWorktimeIndexRouteImport } from './app/routes/_layout/worktime/index'
import { Route as LayoutSupportIndexRouteImport } from './app/routes/_layout/support/index'
import { Route as LayoutShipmentsIndexRouteImport } from './app/routes/_layout/shipments/index'
import { Route as LayoutShipmentRequestsIndexRouteImport } from './app/routes/_layout/shipment-requests/index'
import { Route as LayoutSharingIndexRouteImport } from './app/routes/_layout/sharing/index'
import { Route as LayoutSettingsIndexRouteImport } from './app/routes/_layout/settings/index'
import { Route as LayoutReportsIndexRouteImport } from './app/routes/_layout/reports/index'
import { Route as LayoutPurchasePlannerIndexRouteImport } from './app/routes/_layout/purchase-planner/index'
import { Route as LayoutProfileIndexRouteImport } from './app/routes/_layout/profile/index'
import { Route as LayoutNotificationsIndexRouteImport } from './app/routes/_layout/notifications/index'
import { Route as LayoutNoAccessIndexRouteImport } from './app/routes/_layout/no-access/index'
import { Route as LayoutMyShiftIndexRouteImport } from './app/routes/_layout/my-shift/index'
import { Route as LayoutMessengerIndexRouteImport } from './app/routes/_layout/messenger/index'
import { Route as LayoutMaintenanceIndexRouteImport } from './app/routes/_layout/maintenance/index'
import { Route as LayoutInventoryIndexRouteImport } from './app/routes/_layout/inventory/index'
import { Route as LayoutImplementsIndexRouteImport } from './app/routes/_layout/implements/index'
import { Route as LayoutFieldsIndexRouteImport } from './app/routes/_layout/fields/index'
import { Route as LayoutExpensesIndexRouteImport } from './app/routes/_layout/expenses/index'
import { Route as LayoutEquipmentIndexRouteImport } from './app/routes/_layout/equipment/index'
import { Route as LayoutEmployeesIndexRouteImport } from './app/routes/_layout/employees/index'
import { Route as LayoutAuditLogIndexRouteImport } from './app/routes/_layout/audit-log/index'
import { Route as LayoutAgroCalendarIndexRouteImport } from './app/routes/_layout/agro-calendar/index'
import { Route as SuperadminAuthenticatedDashboardRouteImport } from './app/routes/superadmin/_authenticated/dashboard'
import { Route as LayoutSupportNewRouteImport } from './app/routes/_layout/support/new'
import { Route as LayoutSupportGuideRouteImport } from './app/routes/_layout/support/guide'
import { Route as LayoutSupportTicketIdRouteImport } from './app/routes/_layout/support/$ticketId'
import { Route as LayoutShipmentRequestsMyRouteImport } from './app/routes/_layout/shipment-requests/my'
import { Route as LayoutShipmentRequestsRequestIdRouteImport } from './app/routes/_layout/shipment-requests/$requestId'
import { Route as LayoutMessengerChatIdRouteImport } from './app/routes/_layout/messenger/$chatId'
import { Route as LayoutImplementsImplementIdRouteImport } from './app/routes/_layout/implements/$implementId'
import { Route as LayoutEquipmentEquipmentIdRouteImport } from './app/routes/_layout/equipment/$equipmentId'
import { Route as SuperadminAuthenticatedSupportIndexRouteImport } from './app/routes/superadmin/_authenticated/support/index'
import { Route as LayoutAnalyticsForecastIndexRouteImport } from './app/routes/_layout/analytics/forecast/index'
import { Route as SuperadminAuthenticatedSupportTicketIdRouteImport } from './app/routes/superadmin/_authenticated/support/$ticketId'

const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const LayoutRoute = LayoutRouteImport.update({
  id: '/_layout',
  getParentRoute: () => rootRouteImport,
} as any)
const SuperadminRouteRoute = SuperadminRouteRouteImport.update({
  id: '/superadmin',
  path: '/superadmin',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const LandingIndexRoute = LandingIndexRouteImport.update({
  id: '/landing/',
  path: '/landing/',
  getParentRoute: () => rootRouteImport,
} as any)
const SuperadminLoginRoute = SuperadminLoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => SuperadminRouteRoute,
} as any)
const SuperadminAuthenticatedRoute = SuperadminAuthenticatedRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => SuperadminRouteRoute,
} as any)
const LayoutDashboardRoute = LayoutDashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => LayoutRoute,
} as any)
const LayoutWorktimeIndexRoute = LayoutWorktimeIndexRouteImport.update({
  id: '/worktime/',
  path: '/worktime/',
  getParentRoute: () => LayoutRoute,
} as any)
const LayoutSupportIndexRoute = LayoutSupportIndexRouteImport.update({
  id: '/support/',
  path: '/support/',
  getParentRoute: () => LayoutRoute,
} as any)
const LayoutShipmentsIndexRoute = LayoutShipmentsIndexRouteImport.update({
  id: '/shipments/',
  path: '/shipments/',
  getParentRoute: () => LayoutRoute,
} as any)
const LayoutShipmentRequestsIndexRoute =
  LayoutShipmentRequestsIndexRouteImport.update({
    id: '/shipment-requests/',
    path: '/shipment-requests/',
    getParentRoute: () => LayoutRoute,
  } as any)
const LayoutSharingIndexRoute = LayoutSharingIndexRouteImport.update({
  id: '/sharing/',
  path: '/sharing/',
  getParentRoute: () => LayoutRoute,
} as any)
const LayoutSettingsIndexRoute = LayoutSettingsIndexRouteImport.update({
  id: '/settings/',
  path: '/settings/',
  getParentRoute: () => LayoutRoute,
} as any)
const LayoutReportsIndexRoute = LayoutReportsIndexRouteImport.update({
  id: '/reports/',
  path: '/reports/',
  getParentRoute: () => LayoutRoute,
} as any)
const LayoutPurchasePlannerIndexRoute =
  LayoutPurchasePlannerIndexRouteImport.update({
    id: '/purchase-planner/',
    path: '/purchase-planner/',
    getParentRoute: () => LayoutRoute,
  } as any)
const LayoutProfileIndexRoute = LayoutProfileIndexRouteImport.update({
  id: '/profile/',
  path: '/profile/',
  getParentRoute: () => LayoutRoute,
} as any)
const LayoutNotificationsIndexRoute =
  LayoutNotificationsIndexRouteImport.update({
    id: '/notifications/',
    path: '/notifications/',
    getParentRoute: () => LayoutRoute,
  } as any)
const LayoutNoAccessIndexRoute = LayoutNoAccessIndexRouteImport.update({
  id: '/no-access/',
  path: '/no-access/',
  getParentRoute: () => LayoutRoute,
} as any)
const LayoutMyShiftIndexRoute = LayoutMyShiftIndexRouteImport.update({
  id: '/my-shift/',
  path: '/my-shift/',
  getParentRoute: () => LayoutRoute,
} as any)
const LayoutMessengerIndexRoute = LayoutMessengerIndexRouteImport.update({
  id: '/messenger/',
  path: '/messenger/',
  getParentRoute: () => LayoutRoute,
} as any)
const LayoutMaintenanceIndexRoute = LayoutMaintenanceIndexRouteImport.update({
  id: '/maintenance/',
  path: '/maintenance/',
  getParentRoute: () => LayoutRoute,
} as any)
const LayoutInventoryIndexRoute = LayoutInventoryIndexRouteImport.update({
  id: '/inventory/',
  path: '/inventory/',
  getParentRoute: () => LayoutRoute,
} as any)
const LayoutImplementsIndexRoute = LayoutImplementsIndexRouteImport.update({
  id: '/implements/',
  path: '/implements/',
  getParentRoute: () => LayoutRoute,
} as any)
const LayoutFieldsIndexRoute = LayoutFieldsIndexRouteImport.update({
  id: '/fields/',
  path: '/fields/',
  getParentRoute: () => LayoutRoute,
} as any)
const LayoutExpensesIndexRoute = LayoutExpensesIndexRouteImport.update({
  id: '/expenses/',
  path: '/expenses/',
  getParentRoute: () => LayoutRoute,
} as any)
const LayoutEquipmentIndexRoute = LayoutEquipmentIndexRouteImport.update({
  id: '/equipment/',
  path: '/equipment/',
  getParentRoute: () => LayoutRoute,
} as any)
const LayoutEmployeesIndexRoute = LayoutEmployeesIndexRouteImport.update({
  id: '/employees/',
  path: '/employees/',
  getParentRoute: () => LayoutRoute,
} as any)
const LayoutAuditLogIndexRoute = LayoutAuditLogIndexRouteImport.update({
  id: '/audit-log/',
  path: '/audit-log/',
  getParentRoute: () => LayoutRoute,
} as any)
const LayoutAgroCalendarIndexRoute = LayoutAgroCalendarIndexRouteImport.update({
  id: '/agro-calendar/',
  path: '/agro-calendar/',
  getParentRoute: () => LayoutRoute,
} as any)
const SuperadminAuthenticatedDashboardRoute =
  SuperadminAuthenticatedDashboardRouteImport.update({
    id: '/dashboard',
    path: '/dashboard',
    getParentRoute: () => SuperadminAuthenticatedRoute,
  } as any)
const LayoutSupportNewRoute = LayoutSupportNewRouteImport.update({
  id: '/support/new',
  path: '/support/new',
  getParentRoute: () => LayoutRoute,
} as any)
const LayoutSupportGuideRoute = LayoutSupportGuideRouteImport.update({
  id: '/support/guide',
  path: '/support/guide',
  getParentRoute: () => LayoutRoute,
} as any)
const LayoutSupportTicketIdRoute = LayoutSupportTicketIdRouteImport.update({
  id: '/support/$ticketId',
  path: '/support/$ticketId',
  getParentRoute: () => LayoutRoute,
} as any)
const LayoutShipmentRequestsMyRoute =
  LayoutShipmentRequestsMyRouteImport.update({
    id: '/shipment-requests/my',
    path: '/shipment-requests/my',
    getParentRoute: () => LayoutRoute,
  } as any)
const LayoutShipmentRequestsRequestIdRoute =
  LayoutShipmentRequestsRequestIdRouteImport.update({
    id: '/shipment-requests/$requestId',
    path: '/shipment-requests/$requestId',
    getParentRoute: () => LayoutRoute,
  } as any)
const LayoutMessengerChatIdRoute = LayoutMessengerChatIdRouteImport.update({
  id: '/messenger/$chatId',
  path: '/messenger/$chatId',
  getParentRoute: () => LayoutRoute,
} as any)
const LayoutImplementsImplementIdRoute =
  LayoutImplementsImplementIdRouteImport.update({
    id: '/implements/$implementId',
    path: '/implements/$implementId',
    getParentRoute: () => LayoutRoute,
  } as any)
const LayoutEquipmentEquipmentIdRoute =
  LayoutEquipmentEquipmentIdRouteImport.update({
    id: '/equipment/$equipmentId',
    path: '/equipment/$equipmentId',
    getParentRoute: () => LayoutRoute,
  } as any)
const SuperadminAuthenticatedSupportIndexRoute =
  SuperadminAuthenticatedSupportIndexRouteImport.update({
    id: '/support/',
    path: '/support/',
    getParentRoute: () => SuperadminAuthenticatedRoute,
  } as any)
const LayoutAnalyticsForecastIndexRoute =
  LayoutAnalyticsForecastIndexRouteImport.update({
    id: '/analytics/forecast/',
    path: '/analytics/forecast/',
    getParentRoute: () => LayoutRoute,
  } as any)
const SuperadminAuthenticatedSupportTicketIdRoute =
  SuperadminAuthenticatedSupportTicketIdRouteImport.update({
    id: '/support/$ticketId',
    path: '/support/$ticketId',
    getParentRoute: () => SuperadminAuthenticatedRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/superadmin': typeof SuperadminRouteRouteWithChildren
  '/login': typeof LoginRoute
  '/dashboard': typeof LayoutDashboardRoute
  '/superadmin/login': typeof SuperadminLoginRoute
  '/landing/': typeof LandingIndexRoute
  '/equipment/$equipmentId': typeof LayoutEquipmentEquipmentIdRoute
  '/implements/$implementId': typeof LayoutImplementsImplementIdRoute
  '/messenger/$chatId': typeof LayoutMessengerChatIdRoute
  '/shipment-requests/$requestId': typeof LayoutShipmentRequestsRequestIdRoute
  '/shipment-requests/my': typeof LayoutShipmentRequestsMyRoute
  '/support/$ticketId': typeof LayoutSupportTicketIdRoute
  '/support/guide': typeof LayoutSupportGuideRoute
  '/support/new': typeof LayoutSupportNewRoute
  '/superadmin/dashboard': typeof SuperadminAuthenticatedDashboardRoute
  '/agro-calendar/': typeof LayoutAgroCalendarIndexRoute
  '/audit-log/': typeof LayoutAuditLogIndexRoute
  '/employees/': typeof LayoutEmployeesIndexRoute
  '/equipment/': typeof LayoutEquipmentIndexRoute
  '/expenses/': typeof LayoutExpensesIndexRoute
  '/fields/': typeof LayoutFieldsIndexRoute
  '/implements/': typeof LayoutImplementsIndexRoute
  '/inventory/': typeof LayoutInventoryIndexRoute
  '/maintenance/': typeof LayoutMaintenanceIndexRoute
  '/messenger/': typeof LayoutMessengerIndexRoute
  '/my-shift/': typeof LayoutMyShiftIndexRoute
  '/no-access/': typeof LayoutNoAccessIndexRoute
  '/notifications/': typeof LayoutNotificationsIndexRoute
  '/profile/': typeof LayoutProfileIndexRoute
  '/purchase-planner/': typeof LayoutPurchasePlannerIndexRoute
  '/reports/': typeof LayoutReportsIndexRoute
  '/settings/': typeof LayoutSettingsIndexRoute
  '/sharing/': typeof LayoutSharingIndexRoute
  '/shipment-requests/': typeof LayoutShipmentRequestsIndexRoute
  '/shipments/': typeof LayoutShipmentsIndexRoute
  '/support/': typeof LayoutSupportIndexRoute
  '/worktime/': typeof LayoutWorktimeIndexRoute
  '/superadmin/support/$ticketId': typeof SuperadminAuthenticatedSupportTicketIdRoute
  '/analytics/forecast/': typeof LayoutAnalyticsForecastIndexRoute
  '/superadmin/support/': typeof SuperadminAuthenticatedSupportIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/superadmin': typeof SuperadminRouteRouteWithChildren
  '/login': typeof LoginRoute
  '/dashboard': typeof LayoutDashboardRoute
  '/superadmin/login': typeof SuperadminLoginRoute
  '/landing': typeof LandingIndexRoute
  '/equipment/$equipmentId': typeof LayoutEquipmentEquipmentIdRoute
  '/implements/$implementId': typeof LayoutImplementsImplementIdRoute
  '/messenger/$chatId': typeof LayoutMessengerChatIdRoute
  '/shipment-requests/$requestId': typeof LayoutShipmentRequestsRequestIdRoute
  '/shipment-requests/my': typeof LayoutShipmentRequestsMyRoute
  '/support/$ticketId': typeof LayoutSupportTicketIdRoute
  '/support/guide': typeof LayoutSupportGuideRoute
  '/support/new': typeof LayoutSupportNewRoute
  '/superadmin/dashboard': typeof SuperadminAuthenticatedDashboardRoute
  '/agro-calendar': typeof LayoutAgroCalendarIndexRoute
  '/audit-log': typeof LayoutAuditLogIndexRoute
  '/employees': typeof LayoutEmployeesIndexRoute
  '/equipment': typeof LayoutEquipmentIndexRoute
  '/expenses': typeof LayoutExpensesIndexRoute
  '/fields': typeof LayoutFieldsIndexRoute
  '/implements': typeof LayoutImplementsIndexRoute
  '/inventory': typeof LayoutInventoryIndexRoute
  '/maintenance': typeof LayoutMaintenanceIndexRoute
  '/messenger': typeof LayoutMessengerIndexRoute
  '/my-shift': typeof LayoutMyShiftIndexRoute
  '/no-access': typeof LayoutNoAccessIndexRoute
  '/notifications': typeof LayoutNotificationsIndexRoute
  '/profile': typeof LayoutProfileIndexRoute
  '/purchase-planner': typeof LayoutPurchasePlannerIndexRoute
  '/reports': typeof LayoutReportsIndexRoute
  '/settings': typeof LayoutSettingsIndexRoute
  '/sharing': typeof LayoutSharingIndexRoute
  '/shipment-requests': typeof LayoutShipmentRequestsIndexRoute
  '/shipments': typeof LayoutShipmentsIndexRoute
  '/support': typeof LayoutSupportIndexRoute
  '/worktime': typeof LayoutWorktimeIndexRoute
  '/superadmin/support/$ticketId': typeof SuperadminAuthenticatedSupportTicketIdRoute
  '/analytics/forecast': typeof LayoutAnalyticsForecastIndexRoute
  '/superadmin/support': typeof SuperadminAuthenticatedSupportIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/superadmin': typeof SuperadminRouteRouteWithChildren
  '/_layout': typeof LayoutRouteWithChildren
  '/login': typeof LoginRoute
  '/_layout/dashboard': typeof LayoutDashboardRoute
  '/superadmin/_authenticated': typeof SuperadminAuthenticatedRouteWithChildren
  '/superadmin/login': typeof SuperadminLoginRoute
  '/landing/': typeof LandingIndexRoute
  '/_layout/equipment/$equipmentId': typeof LayoutEquipmentEquipmentIdRoute
  '/_layout/implements/$implementId': typeof LayoutImplementsImplementIdRoute
  '/_layout/messenger/$chatId': typeof LayoutMessengerChatIdRoute
  '/_layout/shipment-requests/$requestId': typeof LayoutShipmentRequestsRequestIdRoute
  '/_layout/shipment-requests/my': typeof LayoutShipmentRequestsMyRoute
  '/_layout/support/$ticketId': typeof LayoutSupportTicketIdRoute
  '/_layout/support/guide': typeof LayoutSupportGuideRoute
  '/_layout/support/new': typeof LayoutSupportNewRoute
  '/superadmin/_authenticated/dashboard': typeof SuperadminAuthenticatedDashboardRoute
  '/_layout/agro-calendar/': typeof LayoutAgroCalendarIndexRoute
  '/_layout/audit-log/': typeof LayoutAuditLogIndexRoute
  '/_layout/employees/': typeof LayoutEmployeesIndexRoute
  '/_layout/equipment/': typeof LayoutEquipmentIndexRoute
  '/_layout/expenses/': typeof LayoutExpensesIndexRoute
  '/_layout/fields/': typeof LayoutFieldsIndexRoute
  '/_layout/implements/': typeof LayoutImplementsIndexRoute
  '/_layout/inventory/': typeof LayoutInventoryIndexRoute
  '/_layout/maintenance/': typeof LayoutMaintenanceIndexRoute
  '/_layout/messenger/': typeof LayoutMessengerIndexRoute
  '/_layout/my-shift/': typeof LayoutMyShiftIndexRoute
  '/_layout/no-access/': typeof LayoutNoAccessIndexRoute
  '/_layout/notifications/': typeof LayoutNotificationsIndexRoute
  '/_layout/profile/': typeof LayoutProfileIndexRoute
  '/_layout/purchase-planner/': typeof LayoutPurchasePlannerIndexRoute
  '/_layout/reports/': typeof LayoutReportsIndexRoute
  '/_layout/settings/': typeof LayoutSettingsIndexRoute
  '/_layout/sharing/': typeof LayoutSharingIndexRoute
  '/_layout/shipment-requests/': typeof LayoutShipmentRequestsIndexRoute
  '/_layout/shipments/': typeof LayoutShipmentsIndexRoute
  '/_layout/support/': typeof LayoutSupportIndexRoute
  '/_layout/worktime/': typeof LayoutWorktimeIndexRoute
  '/superadmin/_authenticated/support/$ticketId': typeof SuperadminAuthenticatedSupportTicketIdRoute
  '/_layout/analytics/forecast/': typeof LayoutAnalyticsForecastIndexRoute
  '/superadmin/_authenticated/support/': typeof SuperadminAuthenticatedSupportIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/superadmin'
    | '/login'
    | '/dashboard'
    | '/superadmin/login'
    | '/landing/'
    | '/equipment/$equipmentId'
    | '/implements/$implementId'
    | '/messenger/$chatId'
    | '/shipment-requests/$requestId'
    | '/shipment-requests/my'
    | '/support/$ticketId'
    | '/support/guide'
    | '/support/new'
    | '/superadmin/dashboard'
    | '/agro-calendar/'
    | '/audit-log/'
    | '/employees/'
    | '/equipment/'
    | '/expenses/'
    | '/fields/'
    | '/implements/'
    | '/inventory/'
    | '/maintenance/'
    | '/messenger/'
    | '/my-shift/'
    | '/no-access/'
    | '/notifications/'
    | '/profile/'
    | '/purchase-planner/'
    | '/reports/'
    | '/settings/'
    | '/sharing/'
    | '/shipment-requests/'
    | '/shipments/'
    | '/support/'
    | '/worktime/'
    | '/superadmin/support/$ticketId'
    | '/analytics/forecast/'
    | '/superadmin/support/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/superadmin'
    | '/login'
    | '/dashboard'
    | '/superadmin/login'
    | '/landing'
    | '/equipment/$equipmentId'
    | '/implements/$implementId'
    | '/messenger/$chatId'
    | '/shipment-requests/$requestId'
    | '/shipment-requests/my'
    | '/support/$ticketId'
    | '/support/guide'
    | '/support/new'
    | '/superadmin/dashboard'
    | '/agro-calendar'
    | '/audit-log'
    | '/employees'
    | '/equipment'
    | '/expenses'
    | '/fields'
    | '/implements'
    | '/inventory'
    | '/maintenance'
    | '/messenger'
    | '/my-shift'
    | '/no-access'
    | '/notifications'
    | '/profile'
    | '/purchase-planner'
    | '/reports'
    | '/settings'
    | '/sharing'
    | '/shipment-requests'
    | '/shipments'
    | '/support'
    | '/worktime'
    | '/superadmin/support/$ticketId'
    | '/analytics/forecast'
    | '/superadmin/support'
  id:
    | '__root__'
    | '/'
    | '/superadmin'
    | '/_layout'
    | '/login'
    | '/_layout/dashboard'
    | '/superadmin/_authenticated'
    | '/superadmin/login'
    | '/landing/'
    | '/_layout/equipment/$equipmentId'
    | '/_layout/implements/$implementId'
    | '/_layout/messenger/$chatId'
    | '/_layout/shipment-requests/$requestId'
    | '/_layout/shipment-requests/my'
    | '/_layout/support/$ticketId'
    | '/_layout/support/guide'
    | '/_layout/support/new'
    | '/superadmin/_authenticated/dashboard'
    | '/_layout/agro-calendar/'
    | '/_layout/audit-log/'
    | '/_layout/employees/'
    | '/_layout/equipment/'
    | '/_layout/expenses/'
    | '/_layout/fields/'
    | '/_layout/implements/'
    | '/_layout/inventory/'
    | '/_layout/maintenance/'
    | '/_layout/messenger/'
    | '/_layout/my-shift/'
    | '/_layout/no-access/'
    | '/_layout/notifications/'
    | '/_layout/profile/'
    | '/_layout/purchase-planner/'
    | '/_layout/reports/'
    | '/_layout/settings/'
    | '/_layout/sharing/'
    | '/_layout/shipment-requests/'
    | '/_layout/shipments/'
    | '/_layout/support/'
    | '/_layout/worktime/'
    | '/superadmin/_authenticated/support/$ticketId'
    | '/_layout/analytics/forecast/'
    | '/superadmin/_authenticated/support/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  SuperadminRouteRoute: typeof SuperadminRouteRouteWithChildren
  LayoutRoute: typeof LayoutRouteWithChildren
  LoginRoute: typeof LoginRoute
  LandingIndexRoute: typeof LandingIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_layout': {
      id: '/_layout'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof LayoutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/superadmin': {
      id: '/superadmin'
      path: '/superadmin'
      fullPath: '/superadmin'
      preLoaderRoute: typeof SuperadminRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/landing/': {
      id: '/landing/'
      path: '/landing'
      fullPath: '/landing/'
      preLoaderRoute: typeof LandingIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/superadmin/login': {
      id: '/superadmin/login'
      path: '/login'
      fullPath: '/superadmin/login'
      preLoaderRoute: typeof SuperadminLoginRouteImport
      parentRoute: typeof SuperadminRouteRoute
    }
    '/superadmin/_authenticated': {
      id: '/superadmin/_authenticated'
      path: ''
      fullPath: '/superadmin'
      preLoaderRoute: typeof SuperadminAuthenticatedRouteImport
      parentRoute: typeof SuperadminRouteRoute
    }
    '/_layout/dashboard': {
      id: '/_layout/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof LayoutDashboardRouteImport
      parentRoute: typeof LayoutRoute
    }
    '/_layout/worktime/': {
      id: '/_layout/worktime/'
      path: '/worktime'
      fullPath: '/worktime/'
      preLoaderRoute: typeof LayoutWorktimeIndexRouteImport
      parentRoute: typeof LayoutRoute
    }
    '/_layout/support/': {
      id: '/_layout/support/'
      path: '/support'
      fullPath: '/support/'
      preLoaderRoute: typeof LayoutSupportIndexRouteImport
      parentRoute: typeof LayoutRoute
    }
    '/_layout/shipments/': {
      id: '/_layout/shipments/'
      path: '/shipments'
      fullPath: '/shipments/'
      preLoaderRoute: typeof LayoutShipmentsIndexRouteImport
      parentRoute: typeof LayoutRoute
    }
    '/_layout/shipment-requests/': {
      id: '/_layout/shipment-requests/'
      path: '/shipment-requests'
      fullPath: '/shipment-requests/'
      preLoaderRoute: typeof LayoutShipmentRequestsIndexRouteImport
      parentRoute: typeof LayoutRoute
    }
    '/_layout/sharing/': {
      id: '/_layout/sharing/'
      path: '/sharing'
      fullPath: '/sharing/'
      preLoaderRoute: typeof LayoutSharingIndexRouteImport
      parentRoute: typeof LayoutRoute
    }
    '/_layout/settings/': {
      id: '/_layout/settings/'
      path: '/settings'
      fullPath: '/settings/'
      preLoaderRoute: typeof LayoutSettingsIndexRouteImport
      parentRoute: typeof LayoutRoute
    }
    '/_layout/reports/': {
      id: '/_layout/reports/'
      path: '/reports'
      fullPath: '/reports/'
      preLoaderRoute: typeof LayoutReportsIndexRouteImport
      parentRoute: typeof LayoutRoute
    }
    '/_layout/purchase-planner/': {
      id: '/_layout/purchase-planner/'
      path: '/purchase-planner'
      fullPath: '/purchase-planner/'
      preLoaderRoute: typeof LayoutPurchasePlannerIndexRouteImport
      parentRoute: typeof LayoutRoute
    }
    '/_layout/profile/': {
      id: '/_layout/profile/'
      path: '/profile'
      fullPath: '/profile/'
      preLoaderRoute: typeof LayoutProfileIndexRouteImport
      parentRoute: typeof LayoutRoute
    }
    '/_layout/notifications/': {
      id: '/_layout/notifications/'
      path: '/notifications'
      fullPath: '/notifications/'
      preLoaderRoute: typeof LayoutNotificationsIndexRouteImport
      parentRoute: typeof LayoutRoute
    }
    '/_layout/no-access/': {
      id: '/_layout/no-access/'
      path: '/no-access'
      fullPath: '/no-access/'
      preLoaderRoute: typeof LayoutNoAccessIndexRouteImport
      parentRoute: typeof LayoutRoute
    }
    '/_layout/my-shift/': {
      id: '/_layout/my-shift/'
      path: '/my-shift'
      fullPath: '/my-shift/'
      preLoaderRoute: typeof LayoutMyShiftIndexRouteImport
      parentRoute: typeof LayoutRoute
    }
    '/_layout/messenger/': {
      id: '/_layout/messenger/'
      path: '/messenger'
      fullPath: '/messenger/'
      preLoaderRoute: typeof LayoutMessengerIndexRouteImport
      parentRoute: typeof LayoutRoute
    }
    '/_layout/maintenance/': {
      id: '/_layout/maintenance/'
      path: '/maintenance'
      fullPath: '/maintenance/'
      preLoaderRoute: typeof LayoutMaintenanceIndexRouteImport
      parentRoute: typeof LayoutRoute
    }
    '/_layout/inventory/': {
      id: '/_layout/inventory/'
      path: '/inventory'
      fullPath: '/inventory/'
      preLoaderRoute: typeof LayoutInventoryIndexRouteImport
      parentRoute: typeof LayoutRoute
    }
    '/_layout/implements/': {
      id: '/_layout/implements/'
      path: '/implements'
      fullPath: '/implements/'
      preLoaderRoute: typeof LayoutImplementsIndexRouteImport
      parentRoute: typeof LayoutRoute
    }
    '/_layout/fields/': {
      id: '/_layout/fields/'
      path: '/fields'
      fullPath: '/fields/'
      preLoaderRoute: typeof LayoutFieldsIndexRouteImport
      parentRoute: typeof LayoutRoute
    }
    '/_layout/expenses/': {
      id: '/_layout/expenses/'
      path: '/expenses'
      fullPath: '/expenses/'
      preLoaderRoute: typeof LayoutExpensesIndexRouteImport
      parentRoute: typeof LayoutRoute
    }
    '/_layout/equipment/': {
      id: '/_layout/equipment/'
      path: '/equipment'
      fullPath: '/equipment/'
      preLoaderRoute: typeof LayoutEquipmentIndexRouteImport
      parentRoute: typeof LayoutRoute
    }
    '/_layout/employees/': {
      id: '/_layout/employees/'
      path: '/employees'
      fullPath: '/employees/'
      preLoaderRoute: typeof LayoutEmployeesIndexRouteImport
      parentRoute: typeof LayoutRoute
    }
    '/_layout/audit-log/': {
      id: '/_layout/audit-log/'
      path: '/audit-log'
      fullPath: '/audit-log/'
      preLoaderRoute: typeof LayoutAuditLogIndexRouteImport
      parentRoute: typeof LayoutRoute
    }
    '/_layout/agro-calendar/': {
      id: '/_layout/agro-calendar/'
      path: '/agro-calendar'
      fullPath: '/agro-calendar/'
      preLoaderRoute: typeof LayoutAgroCalendarIndexRouteImport
      parentRoute: typeof LayoutRoute
    }
    '/superadmin/_authenticated/dashboard': {
      id: '/superadmin/_authenticated/dashboard'
      path: '/dashboard'
      fullPath: '/superadmin/dashboard'
      preLoaderRoute: typeof SuperadminAuthenticatedDashboardRouteImport
      parentRoute: typeof SuperadminAuthenticatedRoute
    }
    '/_layout/support/new': {
      id: '/_layout/support/new'
      path: '/support/new'
      fullPath: '/support/new'
      preLoaderRoute: typeof LayoutSupportNewRouteImport
      parentRoute: typeof LayoutRoute
    }
    '/_layout/support/guide': {
      id: '/_layout/support/guide'
      path: '/support/guide'
      fullPath: '/support/guide'
      preLoaderRoute: typeof LayoutSupportGuideRouteImport
      parentRoute: typeof LayoutRoute
    }
    '/_layout/support/$ticketId': {
      id: '/_layout/support/$ticketId'
      path: '/support/$ticketId'
      fullPath: '/support/$ticketId'
      preLoaderRoute: typeof LayoutSupportTicketIdRouteImport
      parentRoute: typeof LayoutRoute
    }
    '/_layout/shipment-requests/my': {
      id: '/_layout/shipment-requests/my'
      path: '/shipment-requests/my'
      fullPath: '/shipment-requests/my'
      preLoaderRoute: typeof LayoutShipmentRequestsMyRouteImport
      parentRoute: typeof LayoutRoute
    }
    '/_layout/shipment-requests/$requestId': {
      id: '/_layout/shipment-requests/$requestId'
      path: '/shipment-requests/$requestId'
      fullPath: '/shipment-requests/$requestId'
      preLoaderRoute: typeof LayoutShipmentRequestsRequestIdRouteImport
      parentRoute: typeof LayoutRoute
    }
    '/_layout/messenger/$chatId': {
      id: '/_layout/messenger/$chatId'
      path: '/messenger/$chatId'
      fullPath: '/messenger/$chatId'
      preLoaderRoute: typeof LayoutMessengerChatIdRouteImport
      parentRoute: typeof LayoutRoute
    }
    '/_layout/implements/$implementId': {
      id: '/_layout/implements/$implementId'
      path: '/implements/$implementId'
      fullPath: '/implements/$implementId'
      preLoaderRoute: typeof LayoutImplementsImplementIdRouteImport
      parentRoute: typeof LayoutRoute
    }
    '/_layout/equipment/$equipmentId': {
      id: '/_layout/equipment/$equipmentId'
      path: '/equipment/$equipmentId'
      fullPath: '/equipment/$equipmentId'
      preLoaderRoute: typeof LayoutEquipmentEquipmentIdRouteImport
      parentRoute: typeof LayoutRoute
    }
    '/superadmin/_authenticated/support/': {
      id: '/superadmin/_authenticated/support/'
      path: '/support'
      fullPath: '/superadmin/support/'
      preLoaderRoute: typeof SuperadminAuthenticatedSupportIndexRouteImport
      parentRoute: typeof SuperadminAuthenticatedRoute
    }
    '/_layout/analytics/forecast/': {
      id: '/_layout/analytics/forecast/'
      path: '/analytics/forecast'
      fullPath: '/analytics/forecast/'
      preLoaderRoute: typeof LayoutAnalyticsForecastIndexRouteImport
      parentRoute: typeof LayoutRoute
    }
    '/superadmin/_authenticated/support/$ticketId': {
      id: '/superadmin/_authenticated/support/$ticketId'
      path: '/support/$ticketId'
      fullPath: '/superadmin/support/$ticketId'
      preLoaderRoute: typeof SuperadminAuthenticatedSupportTicketIdRouteImport
      parentRoute: typeof SuperadminAuthenticatedRoute
    }
  }
}

interface SuperadminAuthenticatedRouteChildren {
  SuperadminAuthenticatedDashboardRoute: typeof SuperadminAuthenticatedDashboardRoute
  SuperadminAuthenticatedSupportTicketIdRoute: typeof SuperadminAuthenticatedSupportTicketIdRoute
  SuperadminAuthenticatedSupportIndexRoute: typeof SuperadminAuthenticatedSupportIndexRoute
}

const SuperadminAuthenticatedRouteChildren: SuperadminAuthenticatedRouteChildren =
  {
    SuperadminAuthenticatedDashboardRoute:
      SuperadminAuthenticatedDashboardRoute,
    SuperadminAuthenticatedSupportTicketIdRoute:
      SuperadminAuthenticatedSupportTicketIdRoute,
    SuperadminAuthenticatedSupportIndexRoute:
      SuperadminAuthenticatedSupportIndexRoute,
  }

const SuperadminAuthenticatedRouteWithChildren =
  SuperadminAuthenticatedRoute._addFileChildren(
    SuperadminAuthenticatedRouteChildren,
  )

interface SuperadminRouteRouteChildren {
  SuperadminAuthenticatedRoute: typeof SuperadminAuthenticatedRouteWithChildren
  SuperadminLoginRoute: typeof SuperadminLoginRoute
}

const SuperadminRouteRouteChildren: SuperadminRouteRouteChildren = {
  SuperadminAuthenticatedRoute: SuperadminAuthenticatedRouteWithChildren,
  SuperadminLoginRoute: SuperadminLoginRoute,
}

const SuperadminRouteRouteWithChildren = SuperadminRouteRoute._addFileChildren(
  SuperadminRouteRouteChildren,
)

interface LayoutRouteChildren {
  LayoutDashboardRoute: typeof LayoutDashboardRoute
  LayoutEquipmentEquipmentIdRoute: typeof LayoutEquipmentEquipmentIdRoute
  LayoutImplementsImplementIdRoute: typeof LayoutImplementsImplementIdRoute
  LayoutMessengerChatIdRoute: typeof LayoutMessengerChatIdRoute
  LayoutShipmentRequestsRequestIdRoute: typeof LayoutShipmentRequestsRequestIdRoute
  LayoutShipmentRequestsMyRoute: typeof LayoutShipmentRequestsMyRoute
  LayoutSupportTicketIdRoute: typeof LayoutSupportTicketIdRoute
  LayoutSupportGuideRoute: typeof LayoutSupportGuideRoute
  LayoutSupportNewRoute: typeof LayoutSupportNewRoute
  LayoutAgroCalendarIndexRoute: typeof LayoutAgroCalendarIndexRoute
  LayoutAuditLogIndexRoute: typeof LayoutAuditLogIndexRoute
  LayoutEmployeesIndexRoute: typeof LayoutEmployeesIndexRoute
  LayoutEquipmentIndexRoute: typeof LayoutEquipmentIndexRoute
  LayoutExpensesIndexRoute: typeof LayoutExpensesIndexRoute
  LayoutFieldsIndexRoute: typeof LayoutFieldsIndexRoute
  LayoutImplementsIndexRoute: typeof LayoutImplementsIndexRoute
  LayoutInventoryIndexRoute: typeof LayoutInventoryIndexRoute
  LayoutMaintenanceIndexRoute: typeof LayoutMaintenanceIndexRoute
  LayoutMessengerIndexRoute: typeof LayoutMessengerIndexRoute
  LayoutMyShiftIndexRoute: typeof LayoutMyShiftIndexRoute
  LayoutNoAccessIndexRoute: typeof LayoutNoAccessIndexRoute
  LayoutNotificationsIndexRoute: typeof LayoutNotificationsIndexRoute
  LayoutProfileIndexRoute: typeof LayoutProfileIndexRoute
  LayoutPurchasePlannerIndexRoute: typeof LayoutPurchasePlannerIndexRoute
  LayoutReportsIndexRoute: typeof LayoutReportsIndexRoute
  LayoutSettingsIndexRoute: typeof LayoutSettingsIndexRoute
  LayoutSharingIndexRoute: typeof LayoutSharingIndexRoute
  LayoutShipmentRequestsIndexRoute: typeof LayoutShipmentRequestsIndexRoute
  LayoutShipmentsIndexRoute: typeof LayoutShipmentsIndexRoute
  LayoutSupportIndexRoute: typeof LayoutSupportIndexRoute
  LayoutWorktimeIndexRoute: typeof LayoutWorktimeIndexRoute
  LayoutAnalyticsForecastIndexRoute: typeof LayoutAnalyticsForecastIndexRoute
}

const LayoutRouteChildren: LayoutRouteChildren = {
  LayoutDashboardRoute: LayoutDashboardRoute,
  LayoutEquipmentEquipmentIdRoute: LayoutEquipmentEquipmentIdRoute,
  LayoutImplementsImplementIdRoute: LayoutImplementsImplementIdRoute,
  LayoutMessengerChatIdRoute: LayoutMessengerChatIdRoute,
  LayoutShipmentRequestsRequestIdRoute: LayoutShipmentRequestsRequestIdRoute,
  LayoutShipmentRequestsMyRoute: LayoutShipmentRequestsMyRoute,
  LayoutSupportTicketIdRoute: LayoutSupportTicketIdRoute,
  LayoutSupportGuideRoute: LayoutSupportGuideRoute,
  LayoutSupportNewRoute: LayoutSupportNewRoute,
  LayoutAgroCalendarIndexRoute: LayoutAgroCalendarIndexRoute,
  LayoutAuditLogIndexRoute: LayoutAuditLogIndexRoute,
  LayoutEmployeesIndexRoute: LayoutEmployeesIndexRoute,
  LayoutEquipmentIndexRoute: LayoutEquipmentIndexRoute,
  LayoutExpensesIndexRoute: LayoutExpensesIndexRoute,
  LayoutFieldsIndexRoute: LayoutFieldsIndexRoute,
  LayoutImplementsIndexRoute: LayoutImplementsIndexRoute,
  LayoutInventoryIndexRoute: LayoutInventoryIndexRoute,
  LayoutMaintenanceIndexRoute: LayoutMaintenanceIndexRoute,
  LayoutMessengerIndexRoute: LayoutMessengerIndexRoute,
  LayoutMyShiftIndexRoute: LayoutMyShiftIndexRoute,
  LayoutNoAccessIndexRoute: LayoutNoAccessIndexRoute,
  LayoutNotificationsIndexRoute: LayoutNotificationsIndexRoute,
  LayoutProfileIndexRoute: LayoutProfileIndexRoute,
  LayoutPurchasePlannerIndexRoute: LayoutPurchasePlannerIndexRoute,
  LayoutReportsIndexRoute: LayoutReportsIndexRoute,
  LayoutSettingsIndexRoute: LayoutSettingsIndexRoute,
  LayoutSharingIndexRoute: LayoutSharingIndexRoute,
  LayoutShipmentRequestsIndexRoute: LayoutShipmentRequestsIndexRoute,
  LayoutShipmentsIndexRoute: LayoutShipmentsIndexRoute,
  LayoutSupportIndexRoute: LayoutSupportIndexRoute,
  LayoutWorktimeIndexRoute: LayoutWorktimeIndexRoute,
  LayoutAnalyticsForecastIndexRoute: LayoutAnalyticsForecastIndexRoute,
}

const LayoutRouteWithChildren =
  LayoutRoute._addFileChildren(LayoutRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  SuperadminRouteRoute: SuperadminRouteRouteWithChildren,
  LayoutRoute: LayoutRouteWithChildren,
  LoginRoute: LoginRoute,
  LandingIndexRoute: LandingIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
